[project]
name = "flax-illuminant-estimation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "jax[cuda13]>=0.9.0.1",
    "typer>=0.21.1",
    "typing>=3.10.0.0",
]
