[project]
name = "flax-illuminant-estimation"
version = "0.1.0"
description = "A vision transformer (ViT) model for estimating illuminant color in images"
readme = "README.md"
authors = [
    { name = "owo93", email = "iztyle30@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "jax[cuda13]>=0.9.0.1",
    "typer>=0.21.1",
    "typing>=3.10.0.0",
]

[project.scripts]
flax-illuminant-estimation = "flax_illuminant_estimation:main"

[build-system]
requires = ["uv_build>=0.9.4,<0.10.0"]
build-backend = "uv_build"
